# Generated by Django 5.1.4 on 2025-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('construction', 'Construction Company'), ('supplier', 'Material Supplier')], max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_registration_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('services_provided', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
