# Generated by Django 5.1.4 on 2025-01-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0002_companyregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
