# Generated by Django 5.1.4 on 2025-01-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
