# Generated by Django 5.1.4 on 2025-02-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0007_ewallet_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.DeleteModel(
            name='EWallet',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
