# Generated by Django 5.1.4 on 2025-03-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0012_inquiry_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='architectural_plan',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='architectural_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='architectural_style_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='budget_estimate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='building_purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='construction_permit',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='cost_estimation',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='electrical_plan',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='foundation_design',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='hvac_plan',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='land_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='num_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='plumbing_plan',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='site_plan',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='soil_test_report',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='type_of_building',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
