# Generated by Django 5.1.4 on 2025-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0014_order_orderitem_paymentdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdistribution',
            name='booking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
