# Generated by Django 5.1.4 on 2025-03-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0016_company_last_inquiry_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('No-Show', 'No-Show'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
