# Generated by Django 5.1.4 on 2025-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0017_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('No-Show', 'No-Show')], default='Pending', max_length=20),
        ),
    ]
