# Generated by Django 5.1.4 on 2025-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0019_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='signed_agreements/'),
        ),
    ]
