# Generated by Django 5.1.4 on 2025-03-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0020_agreement_service_charge_agreement_signed_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='client',
            new_name='user',
        ),
    ]
