# Generated by Django 5.1.4 on 2025-03-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0021_rename_client_agreement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='architectural_plan',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='architectural_style',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='architectural_style_other',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='budget_estimate',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='building_purpose',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='construction_permit',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='cost_estimation',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='electrical_plan',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='foundation_design',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='hvac_plan',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='num_floors',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='plumbing_plan',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='site_plan',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='soil_test_report',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='special_requirements',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='type_of_building',
        ),
        migrations.CreateModel(
            name='BuildingConstructionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lalpurja', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('napi_naksa', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('tax_clearance', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('approved_building_drawings', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('soil_test_report', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('structural_stability_certificate', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('house_design_approval', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('neighbour_consent', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('iee_report', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('fire_safety_certificate', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('lift_permit', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('parking_layout_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('commercial_special_requirements', models.TextField(blank=True, null=True)),
                ('type_of_building', models.CharField(blank=True, max_length=50, null=True)),
                ('existing_building_details', models.TextField(blank=True, null=True)),
                ('owner_permission_letter', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('existing_structure_analysis', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('renovation_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('noc_municipality', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('waste_management_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/building/')),
                ('area_to_renovate', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('renovation_special_requirements', models.TextField(blank=True, null=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_data', to='ersathi.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineeringConsultingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_building', models.CharField(blank=True, max_length=50, null=True)),
                ('building_purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('num_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('land_area', models.CharField(blank=True, max_length=50, null=True)),
                ('architectural_style', models.CharField(blank=True, max_length=100, null=True)),
                ('architectural_style_other', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('site_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('architectural_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('soil_test_report', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('foundation_design', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('electrical_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('plumbing_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('hvac_plan', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('construction_permit', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('cost_estimation', models.FileField(blank=True, null=True, upload_to='inquiry_files/engineering/')),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_data', to='ersathi.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostConstructionMaintenanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_details', models.TextField(blank=True, null=True)),
                ('maintenance_photos', models.FileField(blank=True, null=True, upload_to='inquiry_files/maintenance/')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_agreed', models.BooleanField(default=False)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_data', to='ersathi.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('language_preference_other', models.CharField(blank=True, max_length=100, null=True)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('training_time', models.CharField(blank=True, max_length=50, null=True)),
                ('training_agreement', models.BooleanField(default=False)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='ersathi.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
