# Generated by Django 5.1.4 on 2025-03-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0022_remove_inquiry_architectural_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
