# Generated by Django 5.1.4 on 2025-04-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0023_order_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
