# Generated by Django 5.1.4 on 2025-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0025_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='completion_certificate',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/building/'),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='completion_certificate_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='construction_phase',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Walls', 'Walls'), ('Roof', 'Roof'), ('Finishing', 'Finishing')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='construction_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='handover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='inspection_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='inspection_reports',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='permit_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='permit_document',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_files/building/'),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='permit_status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='progress_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='progress_photos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='buildingconstructiondata',
            name='warranty_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
