# Generated by Django 5.1.4 on 2025-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0026_buildingconstructiondata_completion_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('No-Show', 'No-Show'), ('Permit Processing', 'Permit Processing'), ('Under Construction', 'Under Construction'), ('Awaiting Inspection', 'Awaiting Inspection'), ('Finishing', 'Finishing'), ('Handover Pending', 'Handover Pending')], default='Pending', max_length=20),
        ),
    ]
