# Generated by Django 5.1.4 on 2025-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0027_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='company_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
